"""add_commission_type_and_rates_to_rules

Revision ID: 3b1e79edfedf
Revises: 9aa26789bc7b
Create Date: 2026-07-10 11:34:12.352103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b1e79edfedf'
down_revision: Union[str, None] = '9aa26789bc7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commission_rules', sa.Column('commission_type', sa.String(length=50), nullable=True))
    op.add_column('commission_rules', sa.Column('slab_configuration', sa.Boolean(), nullable=True))
    op.add_column('commission_rules', sa.Column('payin_od', sa.Float(), nullable=True))
    op.add_column('commission_rules', sa.Column('payout_od', sa.Float(), nullable=True))
    op.add_column('commission_rules', sa.Column('payin_tp', sa.Float(), nullable=True))
    op.add_column('commission_rules', sa.Column('payout_tp', sa.Float(), nullable=True))
    op.add_column('commission_rules', sa.Column('payin_net', sa.Float(), nullable=True))
    op.add_column('commission_rules', sa.Column('payout_net', sa.Float(), nullable=True))
    op.add_column('commission_rules', sa.Column('payin_reward', sa.Float(), nullable=True))
    op.add_column('commission_rules', sa.Column('payout_reward', sa.Float(), nullable=True))
    op.add_column('commission_rules', sa.Column('payin_scheme', sa.Float(), nullable=True))
    op.add_column('commission_rules', sa.Column('payout_scheme', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('commission_rules', 'payout_scheme')
    op.drop_column('commission_rules', 'payin_scheme')
    op.drop_column('commission_rules', 'payout_reward')
    op.drop_column('commission_rules', 'payin_reward')
    op.drop_column('commission_rules', 'payout_net')
    op.drop_column('commission_rules', 'payin_net')
    op.drop_column('commission_rules', 'payout_tp')
    op.drop_column('commission_rules', 'payin_tp')
    op.drop_column('commission_rules', 'payout_od')
    op.drop_column('commission_rules', 'payin_od')
    op.drop_column('commission_rules', 'slab_configuration')
    op.drop_column('commission_rules', 'commission_type')
    # ### end Alembic commands ###
