"""Initial schema

Revision ID: cb47ea9e45a3
Revises: 
Create Date: 2026-07-09 13:29:07.143451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb47ea9e45a3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upload_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('company', sa.String(length=100), nullable=True),
    sa.Column('uploaded_by', sa.String(length=100), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('total_records', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_upload_history_id'), 'upload_history', ['id'], unique=False)
    op.create_table('commission_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upload_id', sa.Integer(), nullable=False),
    sa.Column('sheet_name', sa.String(length=100), nullable=False),
    sa.Column('lob', sa.String(length=100), nullable=True),
    sa.Column('file_type', sa.String(length=100), nullable=True),
    sa.Column('insurance_company', sa.String(length=100), nullable=True),
    sa.Column('product', sa.String(length=100), nullable=True),
    sa.Column('policy_type', sa.String(length=100), nullable=True),
    sa.Column('plan_type', sa.String(length=100), nullable=True),
    sa.Column('sub_product', sa.String(length=100), nullable=True),
    sa.Column('class', sa.String(length=100), nullable=True),
    sa.Column('sub_class', sa.String(length=100), nullable=True),
    sa.Column('make', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('fuel_type', sa.String(length=100), nullable=True),
    sa.Column('body_type', sa.String(length=100), nullable=True),
    sa.Column('vehicle_age_from', sa.Integer(), nullable=True),
    sa.Column('vehicle_age_to', sa.Integer(), nullable=True),
    sa.Column('cpa_status', sa.String(length=100), nullable=True),
    sa.Column('ncb_status', sa.String(length=100), nullable=True),
    sa.Column('partner_type', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=255), nullable=True),
    sa.Column('zone', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('rto', sa.String(length=100), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('raw_json', sa.JSON(), nullable=True),
    sa.Column('validation_status', sa.String(length=50), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['upload_id'], ['upload_history.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commission_rules_id'), 'commission_rules', ['id'], unique=False)
    op.create_table('slab_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commission_rule_id', sa.Integer(), nullable=False),
    sa.Column('payin_type', sa.String(length=50), nullable=True),
    sa.Column('premium_type', sa.String(length=50), nullable=True),
    sa.Column('slab_from', sa.Float(), nullable=True),
    sa.Column('slab_to', sa.Float(), nullable=True),
    sa.Column('payin_od', sa.Float(), nullable=True),
    sa.Column('payout_od', sa.Float(), nullable=True),
    sa.Column('payin_tp', sa.Float(), nullable=True),
    sa.Column('payout_tp', sa.Float(), nullable=True),
    sa.Column('payin_net', sa.Float(), nullable=True),
    sa.Column('payout_net', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['commission_rule_id'], ['commission_rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_slab_details_id'), 'slab_details', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_slab_details_id'), table_name='slab_details')
    op.drop_table('slab_details')
    op.drop_index(op.f('ix_commission_rules_id'), table_name='commission_rules')
    op.drop_table('commission_rules')
    op.drop_index(op.f('ix_upload_history_id'), table_name='upload_history')
    op.drop_table('upload_history')
    # ### end Alembic commands ###
